services:
  app:
    container_name: metro
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - traefik_proxy
    volumes:
      - ./app:/workspace/app
      - ./storage/assets:/workspace/storage/assets
      - ./storage/data:/workspace/storage/data
      - ./storage/sessions:/workspace/storage/sessions
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metro.rule=Host(`metro.pffft.ru`)"
      - "traefik.http.routers.metro.entrypoints=websecure"
      - "traefik.http.routers.metro.tls.certresolver=myresolver"
      - "traefik.http.services.metro.loadbalancer.server.port=8000"

networks:
  traefik_proxy:
    external: true
